### ISSUE TITLE
Cannot import moment-business-days

### ISSUE THREAD

**Issue by IAPBenediktZwoelfer** [kalmecak/moment-business-days#111]
app.js:56 TypeError: Cannot set properties of undefined (setting 'isHoliday')
    at node_modules/moment-business-days/index.js (index.js:7:11)
    at __require2 (chunk-DA74IYYC.js?v=31bda342:17:50)
    at index.js:248:1

**Comment by simplecommerce** [comment]
> app.js:56 TypeError: Cannot set properties of undefined (setting 'isHoliday') at node_modules/moment-business-days/index.js (index.js:7:11) at __require2 (chunk-DA74IYYC.js?v=31bda342:17:50) at index.js:248:1

Did you ever figure out how to fix it?

**Comment by wahibimoh** [comment]
I fixed it by adding the following line to vite.config.js:
resolve: {mainFields: []},

like this: (you can ignore the rest)

```
import { defineConfig } from 'vite'
import { svelte } from '@sveltejs/vite-plugin-svelte'

export default defineConfig({
  build: {
    //minify: false,
  },
  esbuild: { legalComments: 'none' },
  resolve: {mainFields: []}, //<------ this fixed it!
  plugins: [svelte()],
})

```

**Comment by alexeyvokin** [comment]
This solution didn't work for me:

> `resolve: {mainFields: []},`

Does anyone have any idea how this can be fixed in a better way?

Environment:
1) vite **5.2.9**
2) @originjs/vite-plugin-commonjs **1.0.3**
3) @vitejs/plugin-vue **5.0.4**

**Comment by simplecommerce** [comment]
> This solution didn't work for me:
> 
> > `resolve: {mainFields: []},`
> 
> Does anyone have any idea how this can be fixed in a better way?
> 
> Environment:
> 
> 1. vite **5.2.9**
> 2. @originjs/vite-plugin-commonjs **1.0.3**
> 3. @vitejs/plugin-vue **5.0.4**

I haven't tried the suggested fix, I decided to migrate to Luxon instead.

**Comment by wahibimoh** [comment]
Yep, that is what I did as well

**Comment by yodeyer** [comment]
I think the issue is that the latest published version still uses `require` : https://github.com/eduolalo/moment-business-days/blob/v1.2.0/index.js, which is not defined in vite.
The master branch supports ESM imports, but is not published on NPM

**Comment by samausir** [comment]
Importing from the master branch directly did work as suggested above.
`"moment-business-days": "https://github.com/eduolalo/moment-business-days#master",`
